#!/bin/bash

MOOSE_PROFILE_BASE=preallocation-no-reset-4procs mpiexec -np 4 ../combined-opt -i iaea_4_redo46_finerLPs_coarse_ducts.i Problem/restore_original_nonzero_pattern=false Problem/use_hash_table_matrix_assembly=false Problem/error_on_jacobian_nonzero_reallocation=false --color off --error-unused -log_view 2>&1 | tee preallocation-no-reset-4procs.log
MOOSE_PROFILE_BASE=preallocation-reset-4procs mpiexec -np 4 ../combined-opt -i iaea_4_redo46_finerLPs_coarse_ducts.i  Problem/restore_original_nonzero_pattern=true Problem/use_hash_table_matrix_assembly=false Problem/error_on_jacobian_nonzero_reallocation=false --color off --error-unused -log_view 2>&1 | tee preallocation-reset-4procs.log
MOOSE_PROFILE_BASE=hash-4procs mpiexec -np 4 ../combined-opt -i iaea_4_redo46_finerLPs_coarse_ducts.i  Problem/restore_original_nonzero_pattern=true Problem/use_hash_table_matrix_assembly=true Problem/error_on_jacobian_nonzero_reallocation=true --color off --error-unused -log_view 2>&1 | tee hash-4procs.log

MOOSE_PROFILE_BASE=preallocation-no-reset-8procs mpiexec -np 8 ../combined-opt -i iaea_4_redo46_finerLPs_coarse_ducts.i Problem/restore_original_nonzero_pattern=false Problem/use_hash_table_matrix_assembly=false Problem/error_on_jacobian_nonzero_reallocation=false --color off --error-unused -log_view 2>&1 | tee preallocation-no-reset-8procs.log
MOOSE_PROFILE_BASE=preallocation-reset-8procs mpiexec -np 8 ../combined-opt -i iaea_4_redo46_finerLPs_coarse_ducts.i  Problem/restore_original_nonzero_pattern=true Problem/use_hash_table_matrix_assembly=false Problem/error_on_jacobian_nonzero_reallocation=false --color off --error-unused -log_view 2>&1 | tee preallocation-reset-8procs.log
MOOSE_PROFILE_BASE=hash-8procs mpiexec -np 8 ../combined-opt -i iaea_4_redo46_finerLPs_coarse_ducts.i  Problem/restore_original_nonzero_pattern=true Problem/use_hash_table_matrix_assembly=true Problem/error_on_jacobian_nonzero_reallocation=true --color off --error-unused -log_view 2>&1 | tee hash-8procs.log
